Namespace(batch_size=32, data_dir='/root/dataset/Osteoporosis/Sagittal_Contrast_Final_1/', epochs=60, log='logs/Ordinal', lr=0.0001, n_gpu=4, num_classes=3, phase='train', seed=0, weight_decay=0.001, workers=16)
ordinal.py:41: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
  warnings.warn('You have chosen to seed training. '
tensor([2, 0, 2, 2, 0, 0, 1, 2, 0, 0, 0, 2, 0, 0, 2, 1, 0, 1, 1, 0, 0, 2, 0, 1,
        1, 2, 0, 0, 0, 0, 2, 0], device='cuda:0')
Traceback (most recent call last):
  File "ordinal.py", line 250, in <module>
    main(args)
  File "ordinal.py", line 96, in main
    train(model, train_loader, criterion, optimizer,
  File "ordinal.py", line 145, in train
    loss = criterion(output, levels)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 629, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 2582, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
